import {
  ArrowLeft,
  ArrowRight,
  FileText,
  ShieldCheck,
} from "lucide-react";

const sections = [
  {
    title: "1. Platform purpose",
    body: [
      "NovaSales is a demonstration and engineering project for real-time sales intelligence, forecasting, data processing, and explainable AI workflows.",
      "The platform combines historical sales data, simulated continuous sales ingestion, forecasting models, structured APIs, and business intelligence interfaces.",
    ],
  },
  {
    title: "2. Data and forecasts",
    body: [
      "Sales figures displayed by NovaSales are derived from the project's configured datasets and processing pipelines.",
      "Forecasts are generated by the platform's forecasting models and are provided for analytical and demonstration purposes. Forecast values should not be treated as guaranteed future outcomes.",
    ],
  },
  {
    title: "3. AI-generated explanations",
    body: [
      "NovaSales may use Cohere to generate natural-language explanations from structured sales and forecasting context.",
      "The AI explanation layer does not generate or modify the underlying numerical forecast. It provides contextual interpretation of information already produced by the platform.",
    ],
  },
  {
    title: "4. Third-party services",
    body: [
      "The platform may integrate with third-party infrastructure and services including AWS, Cohere, Grafana, and other software dependencies.",
      "Availability, performance, authentication, access restrictions, and service policies of third-party systems are governed by their respective providers.",
    ],
  },
  {
    title: "5. Availability",
    body: [
      "NovaSales is an engineering project and may be modified, restarted, reconfigured, or temporarily unavailable during development and testing.",
      "No guarantee is made regarding continuous availability, production-level service uptime, or uninterrupted access.",
    ],
  },
  {
    title: "6. Acceptable use",
    body: [
      "Users should use the platform only for lawful analytical, educational, demonstration, development, and business-intelligence purposes.",
      "Users should not attempt to compromise the platform, bypass access controls, interfere with services, or use the system to process data they are not authorized to use.",
    ],
  },
  {
    title: "7. Limitation of reliance",
    body: [
      "Information presented by NovaSales is intended to support analysis and demonstration rather than replace professional, financial, operational, or managerial judgment.",
      "Decisions made using information displayed by the platform remain the responsibility of the person or organization making those decisions.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="ns-page">
      <header className="ns-header">
        <div className="ns-container ns-header-inner">
          <a href="/" className="ns-brand">
            <span className="ns-brand-mark" />

            <span>
              <span className="ns-brand-name block">NOVASALES</span>
              <span className="ns-brand-subtitle block">
                Sales Intelligence Platform
              </span>
            </span>
          </a>

          <nav className="ns-nav">
            <a href="/dashboard" className="ns-nav-link">
              Dashboard
            </a>

            <a href="/forecast" className="ns-nav-link">
              Forecast
            </a>

            <a href="/analytics" className="ns-nav-link">
              Analytics
            </a>

            <a href="/ai-insights" className="ns-nav-link">
              AI Insights
            </a>

            <a href="/system" className="ns-nav-link">
              System
            </a>
          </nav>

          <a href="/developers" className="ns-button-secondary">
            Developers
            <ArrowRight size={14} />
          </a>
        </div>
      </header>

      <div className="ns-container">
        <section className="border-b border-[var(--line)] py-14 sm:py-18 lg:py-24">
          <a
            href="/"
            className="ns-link inline-flex items-center gap-2 text-[11px] uppercase tracking-[0.12em]"
          >
            <ArrowLeft size={13} />
            Back to home
          </a>

          <div className="mt-12 grid gap-12 lg:grid-cols-[1fr_0.45fr] lg:items-end lg:gap-20">
            <div>
              <div className="ns-eyebrow">Legal / Terms</div>

              <h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-[0.98] tracking-[-0.065em] text-white sm:text-6xl lg:text-7xl">
                Terms of use.
              </h1>

              <p className="mt-7 max-w-2xl text-base leading-7 text-[var(--text-secondary)]">
                The conditions governing use of the NovaSales demonstration
                and analytics platform.
              </p>
            </div>

            <div className="ns-command-panel">
              <div className="ns-panel-header">
                <div className="flex items-center gap-3">
                  <FileText
                    size={15}
                    className="text-[var(--accent)]"
                  />

                  <span className="ns-panel-title">
                    Document status
                  </span>
                </div>
              </div>

              <div className="p-6">
                <div className="flex items-start gap-3">
                  <ShieldCheck
                    size={17}
                    className="mt-0.5 text-[var(--success)]"
                  />

                  <div>
                    <div className="text-sm font-medium text-white">
                      Project terms
                    </div>

                    <p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">
                      General terms for use of the NovaSales project.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="border-b border-[var(--line)] py-12 lg:py-18">
          <div className="grid gap-px bg-[var(--line)]">
            {sections.map((section) => (
              <article
                key={section.title}
                className="bg-[var(--surface)] p-7 sm:p-9 lg:p-10"
              >
                <h2 className="text-xl font-medium tracking-[-0.03em] text-white">
                  {section.title}
                </h2>

                <div className="mt-5 max-w-4xl space-y-4">
                  {section.body.map((paragraph) => (
                    <p
                      key={paragraph}
                      className="text-sm leading-7 text-[var(--text-secondary)]"
                    >
                      {paragraph}
                    </p>
                  ))}
                </div>
              </article>
            ))}
          </div>
        </section>

        <section className="py-14 lg:py-20">
          <div className="ns-command-panel">
            <div className="p-7 sm:p-9">
              <div className="ns-eyebrow">Related pages</div>

              <div className="mt-6 grid gap-3 sm:grid-cols-3">
                <a
                  href="/privacy"
                  className="ns-button-secondary justify-between"
                >
                  Privacy
                  <ArrowRight size={13} />
                </a>

                <a
                  href="/developers"
                  className="ns-button-secondary justify-between"
                >
                  Developers
                  <ArrowRight size={13} />
                </a>

                <a
                  href="/system"
                  className="ns-button-secondary justify-between"
                >
                  System
                  <ArrowRight size={13} />
                </a>
              </div>
            </div>
          </div>
        </section>
      </div>

      <footer className="ns-footer">
        <div className="ns-container flex flex-col gap-6 py-9 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <div className="font-medium text-[var(--text-secondary)]">
              NovaSales
            </div>

            <div className="mt-1 text-[10px] uppercase tracking-[0.1em] text-[var(--text-muted)]">
              Sales Intelligence Platform
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-x-6 gap-y-3">
            <a href="/" className="ns-footer-link">
              Home
            </a>

            <a href="/terms" className="ns-footer-link">
              Terms
            </a>

            <a href="/privacy" className="ns-footer-link">
              Privacy
            </a>

            <a href="/developers" className="ns-footer-link">
              Developers
            </a>
          </div>
        </div>
      </footer>
    </main>
  );
}